version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wordpress_files:/var/www/html
     ports:
       - "80:80"
     restart: always
     env_file: .env
     environment:
       WORDPRESS_DB_HOST: $DB_HOST
       WORDPRESS_DB_USER: $MYSQL_USER
       WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD

   db:
     image: mysql:5.7
     volumes:
            - db_data:/var/lib/mysql
     restart: always
     env_file: .env
     environment:
       MYSQL_DATABASE: wordpress

volumes:
    wordpress_files:
    db_data:





